

#define BYTE_CODE_MEMORY_STACK_LOAD 0
#define BYTE_CODE_MEM_STACK_LOAD_IMPLICIT 1


#define BYTE_CODE_ADDITION 3
#define BYTE_CODE_SUBTRACTION 4
#define BYTE_CODE_MULTIPLICATION 5 
#define BYTE_CODE_DIVISION 6
#define BYTE_CODE_MODULOS 7

#define BYTE_CODE_ASSIGN_ADDITION 8
#define BYTE_CODE_ASSIGN_SUBTRACTION 9 
#define BYTE_CODE_ASSIGN_MULTIPLICATION 10 
#define BYTE_CODE_ASSIGN_DIVISION 11
#define BYTE_CODE_ASSIGN_MODULOS 12

#define BYTE_CODE_ASSIGN_INCREMENT 13
#define BYTE_CODE_ASSIGN_DECREMENT 14

#define BYTE_CODE_ASSIGN_INCREMENT_LEFT 15
#define BYTE_CODE_ASSIGN_DECREMENT_LEFT 16

#define BYTE_CODE_ASSIGN 17

#define BYTE_CODE_BINARY_ADDITION 22
#define BYTE_CODE_BINARY_SUBTRACTION 23

#define BYTE_CODE_LOAD_VARIABLE_GLOBAL 21
#define BYTE_CODE_LOAD_VARIABLE 22





