#pragma once

#ifndef PARSER_DEFINITIONS_H
#define PARSER_DEFINITIONS_H

#define AST_NODE_NAME_SPACE 1
#define AST_NODE_CODE_BLOCK 2
#define AST_NODE_VARIABLE_DECLARATION 3
#define AST_NODE_FUNCTION_DECLARATION 4

#endif