#pragma once

#ifndef BYTE_CODE_DEFINITIONS_H
#define BYTE_CODE_DEFINITIONS_H

#define BYTECODE_MEM_STACK_LOAD 0
#define BYTECODE_MEM_STACK_LOAD_IMPLICIT 1

#define BYTECODE_LOAD_VARIABLE 2

#define BYTECODE_ADDITION 3
#define BYTECODE_SUBTRACTION 4


#endif