#pragma once

#ifndef BYTE_CODE_DEFINITIONS_H
#define BYTE_CODE_DEFINITIONS_H

#define BYTECODE_MEM_STACK_LOAD 0
#define BYTECODE_MEM_STACK_LOAD_IMPLICIT 1

#define BYTECODE_LOAD_VARIABLE 2

#define BYTECODE_ADDITION 3
#define BYTECODE_SUBTRACTION 4
#define BYTECODE_MULTIPLICATION 5 
#define BYTECODE_DIVISION 6
#define BYTECODE_MODULOS 7


#define BYTECODE_ASSIGN_ADDITION 8
#define BYTECODE_ASSIGN_SUBTRACTION 9 
#define BYTECODE_ASSIGN_MULTIPLICATION 10 
#define BYTECODE_ASSIGN_DIVISION 11
#define BYTECODE_ASSIGN_MODULOS 12

#define BYTECODE_ASSIGN_INCREMENT 13
#define BYTECODE_ASSIGN_DECREMENT 14

#define BYTECODE_ASSIGN_INCREMENT_LEFT 15
#define BYTECODE_ASSIGN_DECREMENT_LEFT 16

#define BYTECODE_ASSIGN 17

#define BYTECODE_POINTER_OPERATIONS_UP 18
#define BYTECODE_POINTER_OPERATIONS_DOWN 19

#define BYTECODE_CALL 20

#define BYTECODE_LOAD_VARIABLE_GLOBAL 21

#define BYTECODE_BINARY_ADDITION 22
#define BYTECODE_BINARY_SUBTRACTION 23



#endif