#pragma once

#ifndef BYTE_CODE_DEFINITIONS_H
#define BYTE_CODE_DEFINITIONS_H

#define BYTECODE_MEM_STACK_LOAD_IMPLICIT 0

#define BYTECODE_ADDITION 1 
#define BYTECODE_SUBTRACTION 2 
#define BYTECODE_MULTIPLICATION 3 
#define BYTECODE_DIVISION 4 
#define BYTECODE_MODULOS 5 

#define BYTECODE_ASSIGN_ADDITION 6 
#define BYTECODE_ASSIGN_SUBTRACTION 7 
#define BYTECODE_ASSIGN_MULTIPLICATION 8 
#define BYTECODE_ASSIGN_DIVISION 9 
#define BYTECODE_ASSIGN_MODULOS 10 

#define BYTECODE_ASSIGN_INCREMENT 11
#define BYTECODE_ASSIGN_DECREMENT 12

#define BYTECODE_ASSIGN 13

#define BYTECODE_POINTER_OPERATION 14
#define BYTECODE_ADDRESS_OPERATION 15

#define BYTECODE_MEM_STACK_LOAD 16

#define BYTECODE_ASSIGN_INCREMENT_LEFT 17
#define BYTECODE_ASSIGN_DECREMENT_LEFT 18

#define BYTECODE_LOAD_VARIABLE 19

#define BYTECODE_CALL_LOCAL 20

#define BYTECODE_POINTER_UP 21

#define BYTECODE_POINTER_DOWN 22

#define BYTECODE_NN 23

#define BYTECODE_CALL 24

#endif