#pragma once

#ifndef BYTE_CODE_DEFINITIONS_H
#define BYTE_CODE_DEFINITIONS_H

#define BYTECODE_MEM_STACK_LOAD_CONST 0 // Load the argument value into stack memory and to stack (arg -> actual value pos in table constsValue) NodeValue

#define BYTECODE_ADDITION 1
#define BYTECODE_SUBTRACTION 2
#define BYTECODE_MULTIPLICATION 3
#define BYTECODE_DIVISION 4
#define BYTECODE_MODULOS 5


#define BYTECODE_LOAD_NAME 6

#define BYTECODE_MEM_STACK_LOAD 7
#define BYTECODE_ASSIGN 8

#define BYTECODE_LOAD_VARIABLE 9

#define BYTECODE_POINTER_OPERATION 10
#define BYTECODE_ADDRESS_OPERATION 11

#define BYTECODE_ASSIGN_ADDITION 12
#define BYTECODE_ASSIGN_SUBTRACTION 13
#define BYTECODE_ASSIGN_MULTIPLICATION 14
#define BYTECODE_ASSIGN_DIVISION 15
#define BYTECODE_ASSIGN_MODULOS 16
#define BYTECODE_ASSIGN_INCREMENT 17
#define BYTECODE_ASSIGN_DECREMENT 18

#define BYTECODE_FUNCTION_CALL 19

#define BYTECODE_IG 20

#endif