#pragma once

#ifndef BYTE_CODE_DEFINITIONS_H
#define BYTE_CODE_DEFINITIONS_H

#define BYTECODE_MEM_STACK_LOAD_IMPLICIT 0 // Load a new value into stack memory and stack execution of argument bytes

#define BYTECODE_ADDITION 1 // Addition
#define BYTECODE_SUBTRACTION 2 // Addition
#define BYTECODE_MULTIPLICATION 3 // Addition
#define BYTECODE_DIVISION 4 // Addition
#define BYTECODE_MODULOS 5 // Addition

#define BYTECODE_ASSIGN_ADDITION 6 // Addition
#define BYTECODE_ASSIGN_SUBTRACTION 7 // Addition
#define BYTECODE_ASSIGN_MULTIPLICATION 8 // Addition
#define BYTECODE_ASSIGN_DIVISION 9 // Addition
#define BYTECODE_ASSIGN_MODULOS 10 // Addition

#define BYTECODE_ASSIGN_INCREMENT 11
#define BYTECODE_ASSIGN_DECREMENT 12

#define BYTECODE_ASSIGN_INCREMENT_LEFT 13
#define BYTECODE_ASSIGN_DECREMENT_LEFT 14

#define BYTECODE_MEM_STACK_LOAD 15

#define BYTECODE_LOAD_VARIABLE 16

#define BYTECODE_ASSIGN 17

#define BYTECODE_POINTER_OPERATION 18
#define BYTECODE_ADDRESS_OPERATION 19

#define BYTECODE_FUNCTION_CALL 20
#define BYTECODE_FUNCTION_CALL_START 21

#endif